type MType={
    id:number;
    title:string | any;
    content:string;
    icon:string;
  }
  
  export type FType={
    id:number,
    title:string,
    content:string;
    image:string;
  }
  
  type NType={
    id:number;
    header:string;
    title:string;
    content:string;
    image:string;
  }
  
  
export const Mlist:MType[] = [
    {
      id:1,
      title:<>Profitability and <br/>Growth</>,
      content:`
        At Creon, we handpick cutting-edge AI projects and offer our community and token holders early access and investment opportunities. Our community actively contributes to the growth and profitability of these projects, creating a dynamic ecosystem of innovation and shared success.
      `,
      icon:'/assets/profit.svg'
    },
    {
      id:2,
      title:<>Transparent & Fair Decentralized <br/>Earnings</>,
      content:`The key element of our proposal is the continuous access to distributed and decentralized earnings generated by AI tools that we provide through their creation or investment in them. This decentralized structure ensures greater transparency and fairness to all participants in the Creon ecosystem.`,
      icon:`/assets/transparent.svg`
    },
    {
      id:3,
      title:<>Launching the <br/>Future</>,
      content:`What's more, Creon is pioneering in offering the first known opportunity to acquire allocations in tokenised AI projects through our Creon Launchpad platform. This gives investors a unique chance for early engagement in the most promising AI projects, opening the door to potentially high returns.`,
      icon:`/assets/early.png`
    },
    {
      id:4,
      title:<>Limitless Possibilities of AI
      <br/>& Crypto</>,
      content:`
        The possibilities offered by the integration of AI and cryptocurrencies are limitless, and we're just beginning to explore them. As pioneers, our journey into uncharted territory is fraught with challenges, but the rewards promise to be equally extraordinary. Creon isn't just about profiting from technological innovation; it's about being part of the process that brings these innovations to life.
      `,
      icon:`/assets/limitless.svg`
    }
  
  ]
  
export const Flist: FType[] =[
  {
    id:1,
    title:'AI Prospects, Market Size, and Development Pace',
    content:`The AI market is one of the most dynamically growing areas of technology. According to reports, the global AI market is expected to reach $190.61 billion by 2025, with a CAGR (Compound Annual Growth Rate) of 36.6%. The key drivers behind this growth include advancements in machine learning, increasing demand for big data analytics, and growing adoption of AI technology across various sectors such as healthcare, finance, and transportation.`,
    image:'/assets/image-1.png'
  },
  {
    id:2,
    title:'AI Tools and Market',
    content:`AI tools refer to the technologies and software that enable computer systems to perform tasks usually requiring human intellect. The market for these tools is dynamic and diverse, encompassing areas such as Natural Language Processing (NLP), machine learning, computer vision, and robotics. With a wide range of applications, AI tools are becoming increasingly indispensable in many sectors, from healthcare to finance, retail, manufacturing, and many others.`,
    image:'/assets/image-2.png'
  },
  {
    id:3,
    title:'AI, Crypto, and NFT Market',
    content:`Artificial Intelligence and blockchain technology are two groundbreaking areas leading new technological innovations. The combination of these two technologies creates intriguing possibilities. For instance, Non-Fungible Tokens (NFTs) can leverage AI to create unique digital artworks or to provide exclusive AI-based services. Meanwhile, cryptocurrencies can benefit from AI by improving security mechanisms, transaction efficiency, and service personalization. Such combination brings substantial benefits for both developers and users, paving the way for unprecedented possibilities.`,
    image:'/assets/image-3.png'
  },
  
]

export const Nlist:NType[] = [
  {
    id:1,
    header:'token',
    title:'The Gateway token to the world of AI',
    content:`Set to debut in the latter half of 2024, the CREON token serves as the pioneering link between cutting-edge AI initiatives and blockchain technology. This innovative token provides NFT and token holders with unparalleled access to our Launchpad, AI tools, and exclusive pre-launch investment prospects.`,
    image:'/assets/frame-1.png'
  },
  {
    id:2,
    header:'revenue',
    title:'Driving income and growth through decentralization',
    content:'CREON NFT and token holders are integral participants in the profit-sharing from our launched AI-based enterprises. We support the development of AI tools, ensuring a steady revenue stream, all while allowing early investors to enjoy the benefits of their support.',
    image:'/assets/frame-2.png'
  },
  {
    id:3,
    header:'launchpad',
    title:'Driving the future of AI Innovation',
    content:`The Creon AI Launchpad, an essential component of our initiative, represents a groundbreaking opportunity in the realm of AI and blockchain. It provides the first known platform for acquiring allocations in tokenized AI projects, offering our community of NFT and CREON token holders early access to innovative and promising AI endeavors.`,
    image:'/assets/frame-3.png'
  }
]

