"use client";
import Image from 'next/image';
import {useState} from 'react';
import styled from 'styled-components';
import { MdKeyboardArrowDown as DownIcon } from "react-icons/md";
import { MdOutlineKeyboardArrowUp as UpIcon } from "react-icons/md";


type MType={
  id:number;
  title:string | any;
  content:string;
  icon:string;


}

const Mlist:MType[] = [
  {
    id:1,
    title:<>Profitability and <br/>Growth</>,
    content:`
      At Creon, we handpick cutting-edge AI projects and offer our community and token holders early access and investment opportunities. Our community actively contributes to the growth and profitability of these projects, creating a dynamic ecosystem of innovation and shared success.
    `,
    icon:'/assets/profit.svg'
  },
  {
    id:2,
    title:<>Transparent & Fair Decentralized <br/>Earnings</>,
    content:`The key element of our proposal is the continuous access to distributed and decentralized earnings generated by AI tools that we provide through their creation or investment in them. This decentralized structure ensures greater transparency and fairness to all participants in the Creon ecosystem.`,
    icon:`/assets/transparent.svg`
  },
  {
    id:3,
    title:<>Early Engagement in Tokenized
    AI <br/>Projects</>,
    content:`What's more, Creon is pioneering in offering the first known opportunity to acquire allocations in tokenised AI projects through our Creon Launchpad platform. This gives investors a unique chance for early engagement in the most promising AI projects, opening the door to potentially high returns.`,
    icon:`/assets/early.svg`
  },
  {
    id:4,
    title:<>Limitless Possibilities of AI
    <br/>& Crypto</>,
    content:`
      The possibilities offered by the integration of AI and cryptocurrencies are limitless, and we're just beginning to explore them. As pioneers, our journey into uncharted territory is fraught with challenges, but the rewards promise to be equally extraordinary. Creon isn't just about profiting from technological innovation; it's about being part of the process that brings these innovations to life.
    `,
    icon:`/assets/limitless.svg`
  }

]
export default function Home() {
  const [active_mission,set_active_mession] = useState<null | number>(null);

  const handleMission = (id:number)=>{
    console.log(id,active_mission,'click')
    if(id == active_mission){
      set_active_mession(null);
      return
    }
    set_active_mession(id);

  }
  return (
    <main>
      <section className={`relative px-5 flex justify-start h-85 lg:h-screen lg:justify-center`}>
        <span className='w-full h-full absolute top-0 left-0 cover' >
          <Image
            className="w-full h-full "
            src="/assets/banner.svg"
            objectFit='cover'
            objectPosition='center'
            alt="Banner"
            fill
            priority
          />
        </span>
        <WrapperText>
          <div>
            The world's first
            platform for Tokenizing
            AI blockchain projects
          </div>
          <div>
            Hold the Creon Pass NFT and earn passive income from AI Tools
          </div>
        </WrapperText>

      </section>
      <SecondSection>
        <div>
          <div>
            <div>
              our mission is to provide unique, confidential AI-based tools, to which you will gain lifetime access through NFT tokens and our CREON token.
            </div>
            <div className='relative w-full h-200 sm:h-250'>
              <Image
                src="/assets/se-banner.png"
                objectFit='cover'
                objectPosition='center'
                fill
                alt="image"
              />
            </div>
          </div>
          <div>
            {Mlist.map(eList => <MCard key={eList.id}>
              <div>
                <div>
                  <Image 
                    src={eList.icon}
                    width={60}
                    height={60}
                    alt="image"
                  />
                </div>
                <div>
                  {eList.title}
                </div>
                <span onClick={()=>handleMission(eList.id)}>
                  {active_mission && active_mission === eList.id?<UpIcon/>:<DownIcon />}
                </span>
              </div>
              <div>
                {active_mission && active_mission === eList.id?eList.content:''}
              </div>

            </MCard>)}
          </div>
        </div>
        
      </SecondSection>
      <ThirdSection className=''>
        <div>
          <div>
            <span>Profiting through</span>
            <span>AI Innovation & Decentralization</span>
          </div>
          <div></div>
        </div>
      </ThirdSection>
    </main>
  )
}

const WrapperText = styled.div`
  position: relative;
  z-index:1;
  align-self: flex-end;
  bottom:50px;
  width:700px;
  display: flex;
  flex-direction: column;
  gap:30px;
  & > div:first-of-type{
    color:var(--white-color);
    font-family: var(--regular-font-ex);
    font-size:2.3rem;
    text-transform:uppercase;
    @media screen and (width <= 850px) {
      font-size: 2rem;
    }
    @media screen and (width <= 550px) {
      font-size: 1.7rem;
    }
  }
  & > div:nth-of-type(2){
    background:linear-gradient(to right, #3D8BFF,#AB23FF);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-size:18px;
    width:80%;
    position:relative;
    &::before,&::after{
      content:'';
      display: block;
      width:100%;
      height:1px;
      background:linear-gradient(to right, #3D8BFF,#AB23FF) ;
      margin:0;
    }
    @media screen and (width <= 450px) {
      width:100%;
    }
  }

  @media screen and (width <= 850px) {
    gap:15px;
    bottom:20px;
  }
  
`
const SecondSection = styled.div`
  padding:50px 0;
  display:flex;
  justify-content: center;
  align-items: center;
  & > div{
    width:var(--main-width);
    display: flex;
    gap:10px;
    padding:10px;
    & > div{
      width:calc(50% - 5px);
      &:first-of-type{
        & > div:first-of-type{
          background:linear-gradient(to right, #3D8BFF,#AB23FF);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          font-size:18px;
          font-size:28px;
          font-family: var(--regular-font-ex);
          @media screen and (width <= 767px) {
              font-size:20px;
          }
        }
      }
      & > :nth-of-type(2){
        display: flex;
      }
      
    }
    @media screen and (width <= 850px) {
      flex-direction: column;
      & > div{
        width:100%;
      }
    }
  }
  


  
`
const MCard = styled.div`
  display:flex;
  width:100%;
  color:var(--white-color);
  border-bottom: 1px solid var(--line-color);
  flex-direction: column;
  align-items: flex-end;
  & > div:first-of-type{
    height:80px;
    display:flex;
    align-items: center;
    padding-top:10px;
    width:100%;
    gap:20px;
    & > div:first-of-type{
      height:80px;
      position:relative;
      display:flex;
      justify-content: center;
      align-items: center;
    }
    & > :nth-of-type(2){
      font-size:15px;
      font-family: var(--regular-font-ex);
    }
    & > span{
      display: flex;
      justify-content: center;
      align-items: center;
      margin-left:auto;
      font-size:20px;
      cursor: pointer;
    }
  }
  & > div:nth-of-type(2){
    padding-bottom:10px;
    width:calc(100% - 80px);
    font-size:13px;
  }
`;

const ThirdSection = styled.div`
  display:flex;
  justify-content: center;
  align-items: center;
  width:100%;
  padding:50px 0px;
  & > div{
    width:var(--main-width);
    padding:20px;
    display:flex;
    flex-direction: column;
    & > div:first-of-type{
      width:100%;
      display:flex;
      flex-direction: column;
      gap:20px;
      & > span{
        display: flex;
        text-transform: uppercase;
        width:fit-content;
        &:first-of-type{
          color:var(--white-color);
          font-family: var(--regular-font-ex);
          align-self: flex-start;
          font-size:2.5rem;
        }
        &:nth-of-type(2){
          background:linear-gradient(to right, #3D8BFF,#AB23FF);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          align-self: flex-end;
          font-size:1.8rem;

        }
      }
    }
    & > div:nth-of-type(2){
      
    }
  }
`

